apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  # These are base64 encoded values
  # postgres in base64
  username: cG9zdGdyZXM=
  # postgres in base64
  password: cG9zdGdyZXM=
